sudo: false
language: java

cache:
  directories:
    - ~/.m2/repository

script:
  - mvn test jacoco:report

after_success:
  - mvn coveralls:report
  - chmod +x scripts/deploy.sh && scripts/deploy.sh 2>&1
